Fixed thrown exception in Manager when having only one item in Manager::$items
Exception: Missing argument 2 for `yii\helpers\BaseArrayHelper::merge()`